require_relative "../lib/Models/users.rb"

u1 = User.create(username: "Charles", password: "Charles1")
u2 = User.create(username: "Chris", password: "Chris1")
u3 = User.create(username: "Justin", password: "Justin1")
u4 = User.create(username: "Luis", password: "Luis1")
u5 = User.create(username: "Minh", password: "Minh1")
u6 = User.create(username: "Nathan", password: "Nathan1")
u7 = User.create(username: "Pratikshya", password: "Pratikshya1")
u8 = User.create(username: "Robert", password: "Robert1")
u9 = User.create(username: "Ryan", password: "Ryan1")
u10 = User.create(username: "Sam", password: "Sam1")
u11 = User.create(username: "Shawn", password: "Shawn1")
u12 = User.create(username: "Kevin", password: "Kevin1")
u13 = User.create(username: "Nicholas", password: "Nicholas1")
u14 = User.create(username: "Thomas", password: "Thomas1")
u15 = User.create(username: "Scott", password: "Scott1")
u16 = User.create(username: "Vidhi", password: "Vidhi1")

r1 = Restaurant.create(name: "Moku Bar")
r2 = Restaurant.create(name: "Antone's Famous Po'Boys")
r3 = Restaurant.create(name: "Arte Pizzeria")
r4 = Restaurant.create(name: "Ballpark Cafe")
r5 = Restaurant.create(name: "Chipotle")
r6 = Restaurant.create(name: "Jason's Deli")
r7 = Restaurant.create(name: "McDonald's")
r8 = Restaurant.create(name: "Schlotsky's")
r9 = Restaurant.create(name: "The Pho Spot")
r10 = Restaurant.create(name: "Your Pie")

s1 = Subscription.create(u1,r1)
s2 = Subscription.create(u1,r9)
s3 = Subscription.create(u2,r2)
s4 = Subscription.create(u2,r6)
s5 = Subscription.create(u2,r7)
s6 = Subscription.create(u3,r5)
s7 = Subscription.create(u3,r10)
s8 = Subscription.create(u4,r2)
s9 = Subscription.create(u4,r3)
s10 = Subscription.create(u5,r10)
s11 = Subscription.create(u5,r6)
s12 = Subscription.create(u6,r3)
s13 = Subscription.create(u7,r8)
s14 = Subscription.create(u7,r2)
s15 = Subscription.create(u8,r1)
s16 = Subscription.create(u8,r10)
s17 = Subscription.create(u9,r4)
s18 = Subscription.create(u10,r5)
s19 = Subscription.create(u10,r9)
s20 = Subscription.create(u11,r1)
s21 = Subscription.create(u11,r6)
s22 = Subscription.create(u12,r7)
s23 = Subscription.create(u13,r1)
s24 = Subscription.create(u13,r10)
s25 = Subscription.create(u14,r2)
s26 = Subscription.create(u15,r3)
s27 = Subscription.create(u16,r4)
s28 = Subscription.create(u16,r5)
s29 = Subscription.create(u16,r7)
s30 = Subscription.create(u16,r8)


